accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path('details/<slug:slug>', views.SingleGroup.as_view(), name='single'),
    path('', views.ListGroups.as_view(), name='list'),
    path('new', views.CreateGroup.as_view(), name='create'),
    path('join/<slug:slug>', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', views.LeaveGroup.as_view(), name='leave')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete')
]

space_ocean/urls.py
from django.contrib import admin
from django.urls import path, include
from os import environ

from . import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('logged-in/', views.LoggedInPage.as_view(), name='logged-in')
]

# Only works if we know the docker network ip and is set in settings.INTERNAL_IPS
if settings.DEBUG and environ.get('NETWORK_IP'):
  import debug_toolbar
  urlpatterns += [
    path('__debug__/', include(debug_toolbar.urls))
  ]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Space Ocean</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>

<body>

  <nav class="navbar mynav" role="navigation" id="navbar">
    <div class="container">
      <div class="navbar-header">
        <a href="{% url 'home' %}" class="navbar-brand mynav">Space Ocean</a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a class="btn btn-simple" href="{% url 'posts:create' %}">Post</a></li>
        <li><a class="btn btn-simple" href="{% url 'groups:list' %}">Groups</a></li>
        <li><a class="btn btn-simple" href="{% url 'groups:create' %}">Create Group</a></li>
        <li><a class="btn btn-simple" href="{% url 'accounts:logout' %}">Log Out</a></li>
        {% else %}
        <li><a class="btn btn-simple" href="{% url 'groups:list' %}">Groups</a></li>
        <li><a class="btn btn-simple" href="{% url 'accounts:login' %}">Log In</a></li>
        <li><a class="btn btn-simple" href="{% url 'accounts:signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container mycontent">
    {% block content %}

    {% endblock %}
  </div>

  <canvas id="canvas"></canvas>
</body>

<script type="text/javascript" src="{% static 'js/master.js' %}"></script>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to Space Ocean!</h1>
{% endblock %}}

templates/logged-in.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon </h1>

{% endblock %}